# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-08 17:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0004_auto_20160408_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
