# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-10 21:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0005_auto_20160408_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='modified_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
