# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-21 20:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0006_auto_20160410_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
