# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-21 22:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0007_advertisement_archived'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertisement',
            options={'ordering': ['-modified_time']},
        ),
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
